# Generated by Django 3.2.3 on 2021-05-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('birth', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=256)),
                ('passport_serial', models.IntegerField()),
                ('passport_date', models.CharField(max_length=10)),
                ('passport_issuer', models.CharField(max_length=256)),
            ],
        ),
    ]
