version: '3.1'

services:
  postgres:
    build: ./postgres
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    build: ./src
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres
