# Generated by Django 3.2.3 on 2021-06-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0003_alter_service_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='services',
        ),
        migrations.AddField(
            model_name='period',
            name='service',
            field=models.CharField(choices=[('технические', 'технические'), ('экспертные', 'экспертные'), ('организационно-методические', 'организационно-методические'), ('информационно-библиографические', 'информационно-библиографические')], default='технические', max_length=64),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
