# Generated by Django 3.2.3 on 2021-06-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0004_auto_20210601_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='service',
            field=models.CharField(choices=[('технические', 'технические'), ('экспертные', 'экспертные'), ('организационно-методические', 'организационно-методические'), ('информационно-библиографические', 'информационно-библиографические'), ('бухгалтерские', 'бухгалтерские')], default='технические', max_length=64),
        ),
    ]
